prometheus:
  prometheusPort: 8080
  prometheusServer: localhost
log:
  level: info
kafka:
  - bootstrapServer: localhost:9092
    topic: kafka-monitoring
    tls:
      enabled: false
      clusterCert: resources/ca.crt
      clientCert: resources/user.crt
      clientKey: resources/user.key
    producerConfig:
     messagesSecond: 2
