{
 "title": "Kafka SLO Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "time",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total SLI",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(kafka_monitoring_cluster_up[1m])) by (cluster) /sum(count_over_time(kafka_monitoring_cluster_up[1m])) by (cluster) *100"
    }
   ]
  },
  {
   "title": "Total SLI (1w)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(kafka_monitoring_cluster_up[1w])) by (cluster) /sum(count_over_time(kafka_monitoring_cluster_up[1w])) by (cluster)*100"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "kafka_monitoring_cluster_up" }
   ]
  },
  {
   "title": "SLO over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(kafka_monitoring_cluster_up[1m])) by (cluster) / sum(count_over_time(kafka_monitoring_cluster_up[1m])) by (cluster) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO over time",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(kafka_monitoring_cluster_up[$time])) by (cluster) / sum(count_over_time(kafka_monitoring_cluster_up[$time])) by (cluster) * 100",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "SLO over time",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(kafka_monitoring_cluster_up[1d])) by (cluster) / sum(count_over_time(kafka_monitoring_cluster_up[1d])) by (cluster) * 100",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}