global:
  scrape_interval:     15s
  evaluation_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'service'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
